### ISSUE TITLE
I can't install GPUminer

### ISSUE THREAD

**Issue by Semartserg** [PoWx-Org/obtc-miner#1]
I fulfill this point 1.Install GPUminer (Windows): (Load GPU Miner ) and after running the installer, a black window appears and immediately disappears.
![Screenshot_2021-05-18-22-03-09-378_com miui videoplayer](https://user-images.githubusercontent.com/84436622/118769939-6174b180-b889-11eb-85cd-3673b3f1ba1b.png)

**Comment by pkvk** [comment]
Type in the command line:

```./ccminer -o stratum+tcp://pool.obtc.me:3390 -u [your address] -p . -a heavyhash -D```

See the official pool page https://pool.obtc.me/ for more information.
